name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22   # match your local version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build   # 👈 only build, no export step

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist   # 👈 Vite outputs to dist, not out
          cname: xyz.example.com # 👈 replace with your domain
